language: common-lisp
sudo: required

python:
  - 2.7

env:
  matrix:
    - LISP=sbcl

branches:
  only:
    - master

os:
  - linux

install:
  - curl -L https://github.com/luismbo/cl-travis/raw/master/install.sh | sh

script:
  - make
  - make run_test
  - make run_bench
