language: common-lisp
sudo: false

env:
  global:
    - PATH=~/.roswell/bin:$PATH
    - ROSWELL_BRANCH=master
    - ROSWELL_INSTALL_DIR=$HOME/.roswell
    - COVERAGE_EXCLUDE=t
  matrix:
    - LISP=sbcl-bin COVERALLS=true

install:
  # Roswell & coveralls
  - curl -L https://raw.githubusercontent.com/snmsts/roswell/$ROSWELL_BRANCH/scripts/install-for-ci.sh | sh
  - git clone https://github.com/fukamachi/cl-coveralls ~/lisp/cl-coveralls
  # Clone cl-libyaml
  - git clone https://github.com/eudoxia0/cl-libyaml.git ~/lisp/cl-libyaml

branches:
  only:
    - master

cache:
  directories:
    - $HOME/.roswell
    - $HOME/.config/common-lisp

install:
  # Roswell & coveralls
  - curl -L https://raw.githubusercontent.com/snmsts/roswell/$ROSWELL_BRANCH/scripts/install-for-ci.sh | sh
  - git clone https://github.com/fukamachi/cl-coveralls ~/lisp/cl-coveralls
  # Clone cl-libyaml
  - git clone https://github.com/adjivas/Taquin.git ~/lisp/n-puzzle

before_script:
  - ros --version
  - ros config

script:
  - make -C ~/lisp/n-puzzle build
  - make -C ~/lisp/n-puzzle test
  - ros -e '(ql:quickload (list :cl-coveralls :ceramic-test))'
        -e '(setf fiveam:*debug-on-error* t
                  fiveam:*debug-on-failure* t)'
        -e '(coveralls:with-coveralls (:exclude (list "t" "main/lib.lisp"))
              (cl-yaml-test:run-tests))'
